import numpy as np

def calculate_revenue_impact(
    monthly_traffic, 
    rate_a, 
    rate_b, 
    average_order_value
):
    """
    Calculates expected additional revenue generated by deploying Variant B.
    
    Parameters:
    - monthly_traffic: Expected number of unique monthly visitors.
    - rate_a: Conversion rate of Variant A (decimal).
    - rate_b: Conversion rate of Variant B (decimal).
    - average_order_value: Mean order value of converting users.
    
    Returns:
    - dict containing monthly and annual revenue gains.
    """
    abs_lift = rate_b - rate_a
    
    additional_monthly_conversions = monthly_traffic * abs_lift
    additional_monthly_revenue = additional_monthly_conversions * average_order_value
    
    additional_annual_conversions = additional_monthly_conversions * 12
    additional_annual_revenue = additional_monthly_revenue * 12
    
    return {
        "abs_lift": abs_lift,
        "monthly_conversions_gain": round(additional_monthly_conversions, 0),
        "monthly_revenue_gain": round(additional_monthly_revenue, 2),
        "annual_conversions_gain": round(additional_annual_conversions, 0),
        "annual_revenue_gain": round(additional_annual_revenue, 2)
    }

def generate_recommendations(z_result, t_result_aov=None, t_result_duration=None, revenue_impact=None, alpha=0.05):
    """
    Generates structured corporate decisions and business rationale based on statistical testing.
    
    Parameters:
    - z_result: Output dictionary from run_z_test (conversion rates)
    - t_result_aov: Output dictionary from run_t_test (Average Order Value)
    - t_result_duration: Output dictionary from run_t_test (Time on Site)
    - revenue_impact: Output dictionary from calculate_revenue_impact
    - alpha: Significance level
    
    Returns:
    - dict containing decision, rationale, risks, and next steps.
    """
    decision = ""
    rationale = []
    risks = []
    next_steps = []
    
    p_value = z_result["p_value"]
    rel_lift = z_result["rel_lift"]
    ci_lower = z_result["ci_lower"]
    ci_upper = z_result["ci_upper"]
    significant = z_result["significant"]
    
    # 1. Primary conversion decision
    if significant:
        if rel_lift > 0:
            decision = "DEPLOY_B"
            decision_text = "Deploy Version B (Treatment)"
            color = "green"
            rationale.append(
                f"Version B achieved a statistically significant increase in conversion rate "
                f"from {z_result['rate_a']:.2%} to {z_result['rate_b']:.2%} "
                f"(Relative Lift of +{rel_lift:.2%})."
            )
            rationale.append(
                f"The result is highly reliable (p-value = {p_value:.4f} is below the threshold alpha = {alpha})."
            )
            rationale.append(
                f"The 95% Confidence Interval for the absolute change is [{ci_lower:.2%}, {ci_upper:.2%}], "
                f"indicating that the change is highly likely to remain positive."
            )
        else:
            decision = "RETAIN_A"
            decision_text = "Retain Version A (Control)"
            color = "red"
            rationale.append(
                f"Version B caused a statistically significant decrease in conversion rate "
                f"from {z_result['rate_a']:.2%} to {z_result['rate_b']:.2%} "
                f"(Relative Lift of {rel_lift:.2%})."
            )
            rationale.append(
                f"The regression is statistically sound (p-value = {p_value:.4f} < alpha = {alpha})."
            )
            rationale.append(
                f"Deploying Version B is expected to harm conversion rates. Do NOT deploy."
            )
    else:
        decision = "INCONCLUSIVE"
        decision_text = "Maintain Experiment (Inconclusive)"
        color = "orange"
        rationale.append(
            f"The difference in conversion rates between Version A ({z_result['rate_a']:.2%}) "
            f"and Version B ({z_result['rate_b']:.2%}) is not statistically significant "
            f"(p-value = {p_value:.4f} is above alpha = {alpha})."
        )
        rationale.append(
            "We cannot confidently state that the observed relative difference "
            f"({rel_lift:+.2%}) is due to the product changes rather than random noise."
        )
        
    # 2. Revenue Impact and secondary metrics implications
    if revenue_impact and decision == "DEPLOY_B":
        annual_gain = revenue_impact["annual_revenue_gain"]
        monthly_gain = revenue_impact["monthly_revenue_gain"]
        rationale.append(
            f"Based on the provided traffic figures, deploying Variant B is estimated to generate "
            f"an additional ${monthly_gain:,.2f} per month, translating to an annual revenue gain of "
            f"${annual_gain:,.2f}."
        )
        
    # 3. Trade-offs and Risks (Secondary continuous metrics)
    # AOV trade-off
    if t_result_aov:
        aov_p = t_result_aov["p_value"]
        aov_lift = t_result_aov["rel_lift"]
        aov_sig = t_result_aov["significant"]
        
        if aov_sig:
            if aov_lift < 0:
                risks.append(
                    f"WARNING: Average Order Value (AOV) decreased by {aov_lift:.2%} (Statistically Significant! "
                    f"p-value = {aov_p:.4f}). This indicates that while more visitors are purchasing, they are buying "
                    f"lower-priced items or smaller basket sizes. Verify that the increase in conversion volume offsets "
                    f"the drop in order value (ARPU)."
                )
            else:
                rationale.append(
                    f"Double Benefit: Average Order Value (AOV) also increased significantly by +{aov_lift:.2%} "
                    f"(p-value = {aov_p:.4f}). Variant B improves both purchasing frequency and purchasing volume."
                )
        else:
            if abs(aov_lift) > 0.01:
                risks.append(
                    f"Note: There is a directional change in AOV of {aov_lift:+.2%}, but it was not statistically "
                    f"significant (p-value = {aov_p:.4f}). We assume AOV remains stable."
                )
                
    # Duration (Engagement) trade-off
    if t_result_duration:
        dur_p = t_result_duration["p_value"]
        dur_lift = t_result_duration["rel_lift"]
        dur_sig = t_result_duration["significant"]
        
        if dur_sig:
            if dur_lift < 0:
                risks.append(
                    f"Note: Session duration (Time on Site) decreased significantly by {dur_lift:.2%} (p-value = {dur_p:.4f}). "
                    f"If the goal of the new checkout is to streamline the experience, this reduction in time on site is "
                    f"actually a positive indicator of frictionless user flow."
                )
            else:
                rationale.append(
                    f"Engagement Lift: Time on Site increased significantly by +{dur_lift:.2%} (p-value = {dur_p:.4f}), "
                    f"indicating higher user engagement in Variant B."
                )
                
    # 4. Actionable Next Steps
    if decision == "DEPLOY_B":
        next_steps.append("Roll out Version B to 100% of website traffic.")
        next_steps.append("Monitor post-deployment metrics for 14 days to confirm conversion and revenue lift.")
        next_steps.append("Archive this experiment and document learnings on layout elements that improved purchases.")
    elif decision == "RETAIN_A":
        next_steps.append("De-escalate Version B traffic to 0% immediately.")
        next_steps.append("Conduct a deep-dive UX audit of Version B to understand why conversion rates dropped.")
        next_steps.append("Iterate on the user interface and plan a new hypothesis (Version C).")
    else:  # Inconclusive
        next_steps.append("Extend the experiment duration to accumulate a larger sample size if the Minimum Detectable Effect (MDE) has not been reached.")
        next_steps.append("Verify if there are any technical bugs or rendering errors on specific browsers/devices that might have suppressed conversions.")
        next_steps.append("If sample sizes are already sufficient according to power analysis, conclude that the change has no meaningful impact and stick with Version A to avoid unnecessary code complexity.")
        
    return {
        "decision": decision,
        "decision_text": decision_text,
        "color": color,
        "rationale": rationale,
        "risks": risks,
        "next_steps": next_steps
    }
